---
# tasks file for post-install

- name: NTP agent on CentOS machine
  yum:
    name: '{{item}}'
    state: present
  when: ansible_distribution == 'CentOS'
  loop:
    - chrony
    - zip
    - unzip
    - wget
    - git
    - httpd

- name: NTP agent on CentOS machine
  service:
    name: '{{item}}'
    state: started
    enabled: yes
  when: ansible_distribution == 'CentOS'
  loop:
    - chronyd
    - httpd

- name: NTP agent on Ubutnu Machine
  apt:
    name: '{{item}}'
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'
  loop:
    - ntp
    - zip
    - unzip
    - wget
    - git
    - apache2

- name: Copy file with owner and permissions
  copy:
    content: 'This machine is managed by the Ansible control machine DO NOT CHANGE ANYTHING MANUALLY'
    dest: /etc/motd

- name: NTP configurations to CentOS machine
  template:
    src: ntp_conf_centos.j2
    dest: /etc/chrony.conf
    backup: yes
  when: ansible_distribution == "CentOS"
  notify:
    - Services should be restarted in CentOS

- name: NTP configuration to Ubuntu machine
  template:
    src: ntp_conf_ubuntu.j2
    dest: /etc/ntp.conf
  when: ansible_distribution == "Ubuntu"
  notify:
    - Services should be restarted in Ubuntu

- name: just Dumpping the file
  copy:
    src: myfile.txt
    dest: /tmp/myfile.txt

- name: creating TEMP folder
  file:
    path: "{{path_folder}}"
    state: directory


