---
- name: configureing webserver
  hosts: webserver
  become: yes
  tasks:
    - name: installing apache server 
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: starting the apache service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    - name: Copy fies to the remote server
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
        backup: yes
